stp/stp

CMakeLists.txt

Commit ffa79942584bc61919f93a97c2394809c9291ff9 (CMakeLists: support
different lib dirs) added possibility to override the directory where
libraries are installed. But when using the PATH type, the path is
being evaluated absolute to the current working directory. The
libraries then end up in a weird local directory suffixed by the lib
string.
In fact we want CMAKE_INSTALL_LIBDIR to be a string like lib or lib64,
so switch PATH to STRING.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>

fix CMAKE_INSTALL_LIBDIR bug I introduced

---

bindings/python/stp/stp.py

The current implementation fails eg. for::
>>> sys.version_info
sys.version_info(major=21, minor=0, micro=1, releaselevel='final',
serial=0)
>>> '21.0.1' > '3'
False
>>> sys.version_info >= (3, 0, 0)
True
I admit it takes some time to get to python21 ;)

fix python3 version comparison

---

include/stp/AST/AST.h
lib/AST/ASTmisc.cpp

There is duplicated code in FatalError implementations. Remove that
and since now FatalError is de facto "noreturn", mark it as such to
silence the compiler yelling.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>

AST: simplify FatalError and mark as noreturn

---

bindings/python/stp/stp.py
tests/api/python/tests.py.in

This fixes various issues with operator overloading in the Python bindings.
Part of this is equivalent to PR #196, but doesn't have the confusing merges and multiple changes. This also adds a thorough test of overloaded operators to the Python API test suite.

Fix operator overloading in Python bindings

---

INSTALL.md
lib/CMakeLists.txt

Fixes the static linking with cryptominisat5.
The changes allow the libraries be installed in arbitrary locations.

Fix static linking

---

include/stp/AST/ASTInternal.h
include/stp/AST/ASTNode.h
lib/AST/ASTNode.cpp
lib/AST/ASTmisc.cpp

Hashing based on memory addresses changes the
order of elements being iterated over depending on the assigned addresses.
This patch introduces a unique ID generated during creation
of the node. And use this for comparison and
hashing functions.
This is one step towards solving #218, it doesn't solve the whole problem yet.
There are a couple of more cases in the code.

Use internal unique ID for ASTNodes for ordering

---

lib/Util/GitSHA1.cpp.in

__DATE__ and __TIME__ prevent reproducible builds. Shot those in head
in case STP_TIMESTAMPS was selected.

GitSHA1: really disable timestamp when requested

---

lib/Simplifier/Simplifier.cpp

assert becomes nop when built with -DNDEBUG. So use abort in
getConstantBit instead of assert.
Signed-off-by: Jiri Slaby <jslaby@suse.cz>

simplifier: use abort() instead of assert(false)

---

lib/Interface/c_interface.cpp

From code:
// FIXME: These typedefs are stupid. They make the code hard to understand!
// These typedefs lower the effort of using the keyboard to type (too
// many overloaded meanings of the word type)
Done.

Replaced node typedef in c_interface implementation

---

appveyor.yml
bindings/python/stp/CMakeLists.txt
bindings/python/stp/library_path.py.in
bindings/python/stp/library_path.py.in_install
tests/api/python/CMakeLists.txt
tests/api/python/tests.py.in

This PR enables testing in AppVeyor. Curiously, the tests pass on my local Windows machine and fail in AppVeyor (running in Release mode in both cases - see the comments in #247).
Also, building against static boost libraries is enabled now and a tiny part of LLVM is built to get a _not_ utility on Windows for running the tests. To keep build times down, the boost build coming with AppVeyor is used and the LLVM files are cached between AppVeyor runs.
GitHub does not display CI information for me right now. The logs for the most recent commit are:
https://travis-ci.org/fkutzner/stp/builds/230315036
https://ci.appveyor.com/project/fkutzner/stp/build/1.0.49

Enabled tests on AppVeyor

---

lib/Parser/CMakeLists.txt

The build steps for the `parser` step were missing a dependency
on the `ASTKind_header` target which would trigger a compilation
failure on macOS when using the "UNIX Makefiles" generator.
This was discovered recently in https://github.com/klee/klee/issues/714
.
I first tried a different approach to fixing this by generating
`ASTKind.cpp` and `ASTKind.h` at configure time and having
CMAKE_CONFIGURE_DEPENDS directory property depend on the files used for
generation. Although this worked it caused STP to be rebuilt from
scratch everytime a re-configure happened.  Although it would be
possible to work around this by only replacing the files if they've
changed at configure time this seems too much work for very little
return. So I went for the simpler change in this commit.

[CMake] Fix #192

---

lib/CMakeLists.txt

STP currently cannot be built with CMake using Xcode as a generator.
This is due to a bug that occurs with TARGET_OBJECTS in current Xcode versions.
The submitted fix is also used similarly in other projects.

circumvent Xcode bug with CMake's TARGET_OBJECTS

---

include/stp/Simplifier/UnsignedIntervalAnalysis.h

I missed these in the first version of the "thread-safe" code.
I discovered this by running my fork of KLEE (with 24 instances of STP) under Intel Inspector. Neither of these affects correctness of the solver, but one does affect correctness of diagnostic output. In any case, we should avoid all data races.

Mark two more global variables as thread_local

---

lib/Parser/CMakeLists.txt

Previously `bison` was being called with `-Dapi.prefix={cvc}` for example, and the braces literally ended up in my `parsecvc.tab.h` header, which upset the C compiler (see sample error messages below). Is it a known quirk of a different version of `bison`?
```
/home1/x/xialiyao/code/stp/build/lib/Parser/parsecvc.tab.h:36:9: error: macro names must be identifiers
#ifndef {CVC}DEBUG
^
/home1/x/xialiyao/code/stp/build/lib/Parser/parsecvc.tab.h:47:5: error: token "{" is not valid in preprocessor expressions
#if {CVC}DEBUG
^
/home1/x/xialiyao/code/stp/build/lib/Parser/parsecvc.tab.h:52:9: error: macro names must be identifiers
#ifndef {CVC}TOKENTYPE
^
/home1/x/xialiyao/code/stp/build/lib/Parser/parsecvc.tab.h:133:15: error: operator "defined" requires an identifier
#if ! defined {CVC}STYPE && …
```

Fix bison prefix

---

appveyor.yml
lib/extlib-abc/aig.h

The STP tests started to fail on my machine when I upgraded to Windows 10. This PR fixes some pointer->long->pointer conversions in aig.h causing trouble when compiling with MSVC, which uses 4-byte longs both for 32-bit and 64-bit binaries.
With this fix, all tests pass on my machine. The `query-files` tests still fail on AppVeyor, but I've seen them pass on AppVeyor when I reactivated the build of `not`.
Edit: this fixes #271.

Fixed pointer->long->pointer conversions in aig.h

---

scripts/starexec/bin/starexec_run_multicore

As the SMT competition supports the parallel execution of SAT solvers,
allow to use cryptominisat in its parallel mode, using all cores that
are available automatically.

starexec: add multicore configuration

---

bindings/python/stp/stp.py.in
include/stp/c_interface.h
lib/Interface/c_interface.cpp
tests/api/python/tests.py.in

Currently, for a pre-build version of STP, it is not possible to (dynamically) find out which version of STP you are running.
This PR:
- Adds versioning calls to the C and Python API
- Adds test-cases to the Python API

Expose STP's versioning information via the C API and the Python API

---

bindings/python/stp/library_path.py.in

Currently, the file `library_path.py` hard-codes the path to the libstp.so, based on the path that was used for CMake. This means that the STP build is tied to the build location, which isn't ideal.
This PR changes `library_path.py` to use both the CMake location and then to check PYTHONPATH.

Python: attempt to dynamically locate libstp.{so, dll}

---

bindings/python/stp/stp.py.in
include/stp/c_interface.h
lib/Interface/c_interface.cpp
tests/api/python/tests.py.in

This PR provide capability inside of the Python and C API to dynamically get and set the underlying SAT solver.
These changes are, regrettably, more verbose than I would have liked. STP uses the enum `stp::UserDefinedFlags::SATSolvers` to capture the current SAT solver. However, because we need validation of which SAT solvers were enabled at build time, it isn't possible to have a generic method to expose setting via the enum.
The most straightforward way here was to have a setter/getter per SAT solver that STP can support.

Add support in Python and C API to dynamically get/set underlying SAT solver

---

lib/CMakeLists.txt

Riss builds its artifacts into separate archive files. When linking
with Riss, both artifacts have to be used, but they have cyclic
dependencies. This can be solved by using linking groups, or by
using the libriss-coprocessor.a archive that is generated by riss.

build: fix linking riss

---

lib/STPManager/STPManager.cpp

PR #304 enables this, but this check prevents it from working. Not sure why the tests aren't catching it.
Also, `width <= 0` is equivalent to `width == 0` as `width` is unsigned.
@TrevorHansen

Allow bitvecs of length >64

---

scripts/starexec/bin/multi-solver.py
scripts/starexec/bin/starexec_run_portfolio

When running with multiple cores, a plain portfolio approach for
several SAT solvers is a viable approach for a small amount of
solvers. When more resources are available, smarter solutions with
sharing should be considered.
This commit adds a script that implements the above idea to a certain
extend. Based on the available resources, the SAT backend uses
the solvers CryptoMiniSat, Riss and MiniSat in parallel. While Riss and
MiniSat get at most one core, CryptoMiniSat is assigned all remainint
resources. This way, we use several solvers, and CryptoMiniSat can share
information about its parallel solver threads.
#287 Implements a first portofolio prototype

starexec: add portfolio script

---

tools/rewrite_rule_gen/rewrite_rule_gen.cpp

The loop variables have type size_t.  On a big endian 64-bit architecture, such as s390x, the %d specifier instructs sprintf to examine only the higher-order 32 bits, which are probably all zero.

Fix two format specifiers.

---

tests/api/python/tests.py.in

This branch fixes three issues with the Python tests:
1. In the "solver" tests, there were no assertion messages, meaning that failures were hard to debug;
2. Also in the "solver" tests, the calculation of the "other solvers" was actually incorrect and raised a Python exception -- it seems these **never** worked (see below);
3. It actually seems that any failures in the Python tests did not record a test failure (`add_test` in CMake only records a failure on a non-zero error code; with the code as it was, `python` would return `0` irrespective as to what happened during test execution!).

Python unit test fixes

---

bindings/python/stp/CMakeLists.txt
bindings/python/stp/library_path.py.in

On Windows, STP's CMake places `libstpwin.dll` inside of the `bin` directory (`CMAKE_RUNTIME_OUTPUT_DIRECTORY`), and not inside of the `lib` directory (`CMAKE_LIBRARY_OUTPUT_DIRECTORY`), which it does on Linux.
This means that the construction of `library_path.py`, which is different to `library_path.py.in_install`, does not work correctly on Windows (as it searches `lib` and not `bin`).
In effect, the file `./bindings/python/stp/library_path.py` gets auto-populated to have Python's search path set to only look in `lib`. This causes the automated Python tests to fail on Windows.
**Note**: I was unsure of the best way to fix this. One thought was to have two `.in` files (one for Windows and one for non-Windows). However, I decided to keep there being one `.in` file, but have some code …

Non-install 'library_path.py' now searches 'lib' and 'bin' folders (now consistent with 'library_path.py.in_install')

---

bindings/python/stp/__init__.py.in

It seems that we do not have consistency between STP's `__init__.py` and the symbols that we try to export via `__all__` in `stp.py`.
STP's Python modules are structured like this:
buildings/python/stp/stp.py
Therefore, if you set PYTHONPATH path to point to `buildings/python` (i.e., the parent directory of the `stp` **folder**) then you do not get our newly-exported symbols, as `import stp` imports the folder (i.e., `__all__.py`) and not the module (i.e., `stp.py`).
This PR (manually) ensures that what's in `__init__.py` is consistent with `__all__`.

Making sure STP's '__init__.py' is consistent with '__all__' in 'stp.py'

---

bindings/python/stp/__init__.py.in
bindings/python/stp/stp.py.in
tests/api/python/tests.py.in

STP's `Solver` Python class only has wrappers for _some_ of STP's C-based API (e.g., it does not expose `vc_bvConcatExpr` or `vc_isBool`).
In some instances, it there is therefor beneficial to be able to work directly with the `ctypes.CDLL` object, rather than the "proxy" `Solver` class.
In the longer term, it is probably worthwhile identifying all of the calls that are missing, and then exposing these via the `Solver` class.
However, in the interim, this PR does resolve that some of these calls are currently inaccessible, and therefore makes STP's Python API "productive".

Exposing the underling `_lib` object from STP's Python API

---

bindings/python/stp/stp.py.in
include/stp/STPManager/UserDefinedFlags.h
include/stp/Sat/CryptoMinisat5.h
include/stp/Sat/SATSolver.h
include/stp/c_interface.h
lib/Interface/c_interface.cpp
lib/STPManager/STP.cpp
lib/Sat/CryptoMinisat5.cpp
tests/api/C/timeout.cpp
tests/api/python/tests.py.in
tools/stp/main.cpp

This PR introduces functionality to utilise Cryptominisat's time-based timeout functionality, to allow checking assertions with a given timeout.
To work entirely correctly, this PR depends on [CMS PR 555](https://github.com/msoos/cryptominisat/pull/555). Without this PR, STP's solver timeouts are based on the starting age of the underlying process and not the age of the solver.
Given this change in CMS, I think it would be best to add more tests to STP that have timeouts across multiple checks/solvers, and where the timeout is shorter than the process age, but still a valid timeout (e.g., a 1 second timeout on a 10 second old process).
I am opening this PR now to allow for early review/comments.

Support time-based timeout when calling Cryptominisat

---

tests/api/C/timeout.cpp
tests/api/python/tests.py.in

This is a quick PR to suppress the time-based timeout tests while I can resolve them.
This is not a permanent solution, but it should resolve the broken build.

Removing the (broken) timeout tests to restore builds on Travis

---

tests/api/C/timeout.cpp
tests/api/python/tests.py.in

Three changes:
- Conflict-based timeout tests are now performed with both CMS and Minisat (both Python and C)
- Python timeout tests are now much more intensive to ensure we hit a timeout (and avoid false negatives during testing)
- C timeout tests have a significantly reduced timeout to ensure we hit a timeout (and avoid false negatives during testing)
Tested locally on my machine, but unclear how the performance of my machine matches Travis. Hopefully my machine is more powerful, and therefore if I hit a timeout, Travis should do as well.

Correcting timeout-based tests to avoid failures on Travis

---

lib/Parser/cvc.y

Bison was producing warnings about this.
I'm not sure if this was ever used, but it's not referenced in the grammar,
and isn't mentioned in the docs.

Remove unused ForDecl node from the grammar.

---

STPConfig.cmake.in

This fixes build for projects that have dependency on STP, but not on Cryptominisat.

Search for cryptominisat before using its targets in STPConfig.cmake.

---

lib/Parser/cvc.y

The following rules were conflicting:
ArrayUpdateExpr : Expr WITH_TOK Updates
Updates : '[' Expr ']' ASSIGN_TOK Expr
| Updates WITH_TOK '[' Expr ']' ASSIGN_TOK Expr
I think it was intended to allow
a [ e1 ] := val
OR
a WITH [ e1 ] := val

Fix bison warning "rule useless in parser due to conflicts"

---

include/stp/c_interface.h
lib/Interface/c_interface.cpp
tests/api/python/tests.py.in

Inside of STP's Python API there was a call to a (non-existent) function of `vc_bvRemExpr`. If using the SMT front-end, the operation `bvurem` gets directly mapped to `BVMOD`.
Given that someone had "already made the mistake" of presuming that `vc_bvRemExpr` existed (e.g., `vc_sbvRemExpr` *does* exist), I provided an implementation that maps (at the API-level) from `vc_bvRemExpr` to `BVMOD`.
An alternative would have been to fix the Python API such that `rem` and `rrem` called `vc_bvModExpr` -- however, adding `vc_bvRemExpr` facilitate API consistency seemed like the better approach.
Tests have been added that would fail on older versions of STP, but give a correct value after this PR.
Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

Provide an implementation of 'vc_bvRemExpr' to allow for API consistency

---

STPConfig.cmake.in

@msoos many thanks for the quick fix!  You just got the string comparison operator wrong, and we get this error in KLEE:
```
CMake Error at /Users/cristic/stp/stp.git/build/STPConfig.cmake:15 (if):
if given arguments:
"" "==" "ON"
```
This trivial patch fixes it.

Fixed operator in STPConfig.cmake.in

---

scripts/travis-cmake.sh

The build scripts that Travis runs point to @msoos's personal copy of Lingeling -- this repo recently got changed to not have a `./configure` script and to use CMake instead.
See: https://github.com/msoos/lingeling-ala/commit/6848f4e105193fd923ce4daf761c85168d6aa32f
This PR fixes Travis's steps to use CMake rather than calling `./configure` for Lingeling.
@msoos do you think it is worthwhile adding `msoos/minisat`, `msoos/cryptominisat`, `conp-solutions/riss`, `klee/klee-uclibc`, `msoos/fuzzsmt`, `msoos/lingeling-ala` and `msoos/boolector-1.5.118` as submodules to STP? This would avoid these breakages.
These list of repos are those which come from `scripts/travis-cmake.sh`.
Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

Ensuring that STP's Travis scripts match the lingeling test repo

---

tools/stp/main_common.cpp

Ensuring that STP's output is (at most) line buffered.
See: https://github.com/stp/stp/issues/363

Use linebuf

---

lib/Interface/CMakeLists.txt

If you use the `ninja` generator with STP, then it becomes clear that STP's build system does work even when there are no changes:
```
[avj@tempvm build]$ ninja
[1/1] Running utility command for CopyPublicHeaders
LEGACY: Copying c_interface.h to /home/avj/clones/stp/master/build/include/stp
LEGACY: Copying cpp_interface.h to /home/avj/clones/stp/master/build/include/stp
[avj@tempvm build]$ ninja
[1/1] Running utility command for CopyPublicHeaders
LEGACY: Copying c_interface.h to /home/avj/clones/stp/master/build/include/stp
LEGACY: Copying cpp_interface.h to /home/avj/clones/stp/master/build/include/stp
[avj@tempvm build]$ ninja
[1/1] Running utility command for CopyPublicHeaders
LEGACY: Copying c_interface.h to /home/avj/clones/stp/master/build/include/stp
LEGACY: Copying cpp_interface.h …
```

Ensuring that all CMake targets are correct to support no-op builds

---

include/stp/cpp_interface.h
lib/Interface/cpp_interface.cpp
tests/query-files/unit_test/function_pop.smt2

As identified in https://github.com/stp/stp/issues/365,  the creation of functions can allow for symbols to escape having their reference count decreased to zero, and therefore their lifetimes are longer than we would expect.
```
(push 1)
(declare-fun x!2 () Bool)
(define-fun x!3 () Bool (not x!2))
(pop 1)
(assert (not x!2))
(check-sat)
```
After popping `x!2` and `x!3`, it should not be possible to refer to `x!2`, but STP allows this.
This PR reworks the symbol/function scopes inside of STP such that popping a frame *also* removes the functions declared in that scope.
I opted to keep a pointer to the "global" function context and then remove the popped functions during destruction of a frame.
An alternative would be change `Cpp_interface::applyFunction` to search through all of the …

Initial work on improving scopes such that symbols are correctly removed

---

include/stp/cpp_interface.h
lib/Interface/cpp_interface.cpp
tests/query-files/unit_test/func_decl_zeroth_scope.smt2

When I implemented scopes, there was a bug where the copy constructor would get called twice when creating and then adding a scope to the vector of all scopes.
This "double creation" meant that functions were cleaned-up at the wrong time.
This PR changes it such that frames are only created once. An option here would have been to define a move constructor and use `emplace_back` (rather than frames being a vector of pointers) -- @msoos do you have a preference here?
Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

Ensuring that we do not create double frames when creating a new frame (closes #385)

---

README.markdown

stp is now in Homebrew/core: https://github.com/Homebrew/homebrew-core/pull/75877
Not sure if this is something you'd like to advertise in your README, but opening this just in case it is.

Add Homebrew installation instructions

---

lib/ToSat/ToSATAIG.cpp

Issue #396 documented a case where STP was crashing when using a build
of CMS that had 'BreakID' enabled. Such a configuration of CMS can
return `l_False` for a `solve` check, but *also* return `true` on a call
to `okay`.
This led to a crash in `ConstructCounterExample` where STP expected the
underlying SAT solver to have a satisfying model, when actually it had
reported UNSAT.
This commit makes it such that `ToSATAIG::runSolver` results the value
of `SATSolver::solve` and not `SATSolver::okay`.
Signed-off-by: Andrew V. Jones <andrewvaughanj@gmail.com>

`ToSATAIG::runSolver` now returns the value of `SATSolver::solve`

---

CMakeLists.txt
lib/Sat/CryptoMinisat5.cpp
lib/Simplifier/DifficultyScore.cpp

This PR fixes some warnings (except for some warnings coming from ABC, which should be fixed on the ABC side, and some warnings can't be fixed properly without C++17), slightly modernizes CMake and adds the ability to suppress warnings at all.
Each commit is a separate edit.
Closes #409.

Fix various warning issues

---

CMakeLists.txt

At the moment, `stp` can be conveniently used together with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) in other projects.
But CMake output from `stp` a bit noisy. And can be confusing for other developers, because they can see warning messages like "Testing is disabled" that comes from `stp` and unrelated their projects.
In this PR I changed messages type from `STATUS` to `DEBUG` because the information like "Boost -- adding '${Boost_LIBRARY_DIRS}' to link directories" is for the `stp` developers. [The documentation](https://cmake.org/cmake/help/latest/command/message.html) says that the purpose of `DEBUG` is "Detailed informational messages intended for developers working on the project itself as opposed to users who just want to build it.". So looks …

Beautify CMake messages

---

CMakeLists.txt
tools/stp/CMakeLists.txt
tools/stp_simple/CMakeLists.txt

Adds an option that disables the build of executable files. This is useful if `stp` is being used as a library. Otherwise, when using the `install` rule, the `stp` application is installed with the product.

Add BUILD_EXECUTABLES option

---

include/stp/c_interface.h

In the C interface, the comment for `vc_bvExtract(vc, e, high, low)` says the bit-width is `high - low`. However, as this operation is inclusive for both `high` and `low`, the resulting bit-width should be `high - low +1`

Fix bvExtract interface comment

---

CMakeLists.txt
lib/NodeFactory/CMakeLists.txt
lib/Parser/CMakeLists.txt
lib/STPManager/CMakeLists.txt
lib/Sat/CryptoMinisat5.cpp
lib/Simplifier/CMakeLists.txt
lib/Simplifier/DifficultyScore.cpp
lib/Simplifier/Simplifier.cpp
lib/extlib-abc/CMakeLists.txt
lib/extlib-abc/aig.h
lib/extlib-abc/cnf_short.h
lib/extlib-abc/vecPtr.h
lib/extlib-abc/vecStr.h
tests/CMakeLists.txt
tests/api/C/array-cvcl-02.cpp
tests/api/C/b4-c2.cpp
tests/api/C/example_broken.cpp
tests/api/C/getbv.cpp
tests/api/C/mdempsky.cpp
tests/api/C/parsefile-using-cinterface.cpp
tests/api/C/stp-bool.cpp
tests/api/C/stp-counterex.cpp
tests/api/C/stp-div-001.cpp
tests/api/C/stp-even-eqn-assert.cpp

Enable warnings as errors (`-Werror`) while building with GCC/clang, and
fix code (and associated tests) such that STP builds across: gcc-7,
gcc-9, gcc-10, clang-7, clang-8, clang-9, clang-10, clang-11 on Linux.
Errors from external libraries (e.g., MiniSat) are marked as `SYSTEM`
(via CMake) and errors in 'internal' libraries (e.g., extlib-abc) are
suppressed via `pragmas`, which work with both GCC and clang. Selective
files in STP have explicit warnings disabled via CMake.
Treating warnings as errors is not enabled when compling with MSVC.
Signed-off-by: Andrew V. Jones <andrewvaughanj@gmail.com>

Treat warnings as errors

---

CMakeLists.txt
tools/stp/CMakeLists.txt

In this PR I modernized Boost usage by using [imported targets](https://cmake.org/cmake/help/latest/module/FindBoost.html#imported-targets). But the feature was introduced in CMake 3.5, so I bumped the version. But KLEE uses [the same version](https://github.com/klee/klee/blob/0ba95edbad26fe70c8132f0731778d94f9609874/CMakeLists.txt#L13), so I hope it's okay :)
Made the same PR for [cryptominisat](https://github.com/msoos/cryptominisat/pull/666).

Modernize Boost usage

---

lib/Simplifier/StrengthReduction.cpp

Older compilers (see #430) currently fail building STP master due to the unnecessary use of a SCARY iterator. This PR simply replaces the written out type with an `auto` use, which will deduce the correct iterator type.

Remove the unnecessary use of a SCARY iterator that may break on older compilers

---

docs/smt-input-language.rst

Page: https://stp.readthedocs.io/en/latest/smt-input-language.html. "For a longer description please read [this PDF]". Here the link is broken. After discussion with @aytey changed the link to https://smtlib.cs.uiowa.edu/.

Fixed the broken link on SMT-LIBv2 documentation.

---

CMakeLists.txt
Dockerfile

I rewrote the Dockerfile to address a few perceived deficiencies, though possibly the right thing is to do (in the future) is to use the `./scripts/deps/` scripts so that the logic is not duplicated.
1. I upgraded the builder image to Ubuntu 22.04 from Ubuntu 16.04.
2. I removed the `LABELS` since these were copied over from CryptoMiniSat and not appropriate for STP.
3. I moved away from building M4RI to installing it from the repository, as CMS instructs in its README.
4. I restructured the `apt-get install` to follow recommended Dockerfile best practices, e.g., with each dependency on its own line, sorted alphabetically, for cleaner diffs. I also reduced the number of times we have to run `apt-get update`.
5. I removed the use of experimental compiler toolchains …

Rewrite Dockerfile

---

include/stp/ToSat/BitBlaster.h
lib/ToSat/BitBlaster.cpp

There were [compilation errors](https://github.com/misonijnik/klee/actions/runs/2954874974/jobs/4918669387) during the build of the master branch of stp on KLEE 2.3 CI. This commit fixes them.

Fix compilation error on libstdc++-7-dev

---

include/stp/AST/ASTNode.h

Otherwise we see errors like this with gcc13:
```
include/stp/AST/ASTNode.h:77:3: error: 'uint8_t' does not name a type
```

[gcc 13] include cstdint for *int*_t

---

tools/stp/main_common.cpp

This code called sbrk(4000000) and beyond error checking ignored the result meaning the 4MB of address space allocated could never be used without another call to sbrk and reference to INITIAL_MEMORY_PREALLOCATION_SIZE, but nothing in the repo does either.

Remove nonsensical sbrk usage

---

CMakeLists.txt
appveyor.yml
include/stp/AST/ASTBVConst.h
include/stp/Simplifier/Simplifier.h
include/stp/Simplifier/SubstitutionMap.h
tests/api/C/counter-example-reading.cpp
tests/api/C/timeout.cpp
tools/stp/main_common.cpp

This gets the windows build closer to working.
It also changes the c++ compiler to a minimum of c++-17, which is the same as cryptominisat requires. If this causes problems, it can be changed back and just results in more warnings.

Partially fix Appveyor (windows) automated build.

---

bindings/python/stp/CMakeLists.txt

The distutils module was deprecated in python 3.10, and will not be installed by default starting in python 3.12.  See https://peps.python.org/pep-0632/ for more information.  This PR uses sysconfig instead of distutils to find the python library directory.

Use sysconfig, not distutils, to find python root

---

lib/AST/genkinds.pl

Currently the generator puts the time of the build in the file, making the results different in each rebuild. Use $SOURCE_DATE_EPOCH to set the timestamp, if the variable is defined.
See https://reproducible-builds.org/docs/source-date-epoch/ for background and the definition of the variable.
The code modification is based on
https://reproducible-builds.org/docs/source-date-epoch/#perl.
Also, fix typo in the header.

Make timestamp in generated file use $SOURCE_DATE_EPOCH

---

lib/Interface/cpp_interface.cpp

Hello, maintainers,
I added the dummy (not changing any solver behavior) interface for the `diagnostic-output-channel` option support. 
This is used in PySMT as a minimal requirement for an SMT solver, and this is why I added this.
https://github.com/pysmt/pysmt/blob/71c35b0b82f7ea63240218777940bed06a18c60c/pysmt/smtlib/solver.py#L47
Because this is a small, harmless change, I hope you will merge this.

Added dummy diagnostic-output-channel support
